version: "3.8"

services:
  wsgi_app:
    build: .
    container_name: tv369
    image: ankitb4/tv390_backend:1.1
    ports:
      - 8000:8000
    volumes:
      - .:/app

    command: >
      sh -c "python3 manage.py migrate &&
             gunicorn tv369_backend.wsgi:application -w 2 -b :8000 --reload
            "
    env_file:
      - ./.env
